### ISSUE TITLE
Question about ViewState instantiation 

### ISSUE THREAD

**Issue by ranhsd** [cardoso/ReduxMovieDB#4]
Hi @cardoso , Really like this example... Good job!

I only have one question. I noticed that you created ViewState objects which receive  the main state and return the state for the specific view. I tried to test your app and noticed that the ViewState objects (for example: MovieListViewState) init function is being called several times. Actually it is being called when any action is being dispatched and I don't know if it is a best practice.

Did you noticed that while developing this example? 

BTW! I tried to integrate **skipRepeats** into your project by implementing the **Equatable** protocol but its still calling the init function a lot of times

**Comment by cardoso** [comment]
@ranhsd I can take a look into implementing it in the weekend. 

But if you can submit a PR, I'll be happy to merge it. :)

Thanks for the suggestion!

**Comment by fbernutz** [comment]
Hi, 
since [ReSwift 4.0.1](https://github.com/ReSwift/ReSwift/releases/tag/4.0.1) `skipRepeats` is on b< default when the SubStates are Equatable. After doing this, I tested it and `newState` for MovieList and MovieDetail is called a few times less. So I hope it's fine, if I add a PR to make the two ViewStates Equatable.

**Comment by fbernutz** [comment]
@cardoso Should this issue stay open or can it be closed?

**Comment by cardoso** [comment]
Closed. Thanks @fbernutz
